# dbt_project.yml

name: 'adventure_works'
version: '1.0.0'
config-version: 2

profile: 'adventure_works'

model-paths: ["models"]
test-paths: ["tests"]
data-paths: ["data"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  adventure_works:
    +schema: dbt_brenotcneto
    +database: EQUATORIAL
    +materialized: table  # Configuração global para materializar como tabela
